export default foodList = [
  'Almond',
  'Apple',
  'Apricot',
  'Artichoke',
  'Asparagus',
  'Avocado',
  'Bamboo shoot',
  'Banana',
  'Barley',
  'Bean',
  'Blackberry',
  'Black-eyed bean',
  'Blueberry',
  'Bonito',
  'Broad bean',
  'Broccoli',
  'Brussels sprouts',
  'Buckwheat',
  'Burdock',
  'Butter',
  'Butter bean',
  'Buttermilk',
  'Button mushroom',
  'Cabbage',
  'Cacao bean',
  'Canola oil',
  'Carrot',
  'Casein',
  'Cauliflower',
  'Celery',
  'Cheese',
  'Cherry',
  'Chestnut',
  'Chicken',
  'Chicory',
  'Chinese cabbage',
  'Coconut oil',
  'Coffee bean',
  'Corn',
  'Corn oil',
  'Cotton seed',
  'Cranberry',
  'Cream',
  'Crustaceans',
  'Cucumber',
  'Custard',
  'Date',
  'Deer',
  'Duck',
  'Eel',
  'Egg plant',
  'Endive',
  'Fructose',
  'Garlic',
  'Ghrkin',
  'Ginger',
  'Ginkgo nut',
  'Globfish',
  'Glucose',
  'Goat',
  'Grape',
  'Grapefruit',
  'Grapeseed oil',
  'Green soybean',
  'Groundnut oil',
  'Guava',
  'Honey',
  'Hop',
  'Horse',
  'Horse Mackerel',
  'Horseradish',
  'Huckleberry',
  'Ice cream',
  'Japanese pear',
  'Japanese persimmon',
  'Japanese plum',
  'Kale',
  'Kidney bean',
  'Kiwi',
  'Konjac',
  'Kyona',
  'Lactose',
  'Leek',
  'Lemon',
  'Lentil',
  'Lettuce',
  'Lima bean',
  'Lime',
  'Loquat',
  'Mackerel',
  'Makuwauri  melon',
  'Mango',
  'Melon',
  'Mineral water',
  'Mitsuba',
  'Mume plum',
  'Mustard oil',
  'Mustard Spinach',
  'Nectarine',
  'Nira',
  'Okra',
  'Olive oil',
  'Onion',
  'Orange',
  'Orange pulp',
  'Papaya',
  'Parsley',
  'Parsnip',
  'Passion fruit',
  'Peach',
  'Peanut',
  'Pear',
  'Peas',
  'Pecan',
  'Pegia',
  'Peppermint',
  'Percifomes',
  'Pineapple',
  'Popcorn',
  'Potato',
  'Prune',
  'Pumpkin',
  'Qing-geng-cai',
  'Quince',
  'Radish leaf',
  'Radish root',
  'Rapeseed',
  'Raspberry',
  'Rice',
  'Ricebran oil',
  'Royal Jelly',
  'Rye',
  'Safflower seed',
  'Salmon',
  'Salsify',
  'Sansho',
  'Sea Bass',
  'Sea Bream',
  'Sesame seed',
  'Shallot',
  'Sheep',
  'Shelled mollusc',
  'Shiitake  mushroom',
  'Shungiku',
  'Sour cream',
  'Soybean',
  'Spearmint',
  'Spinach',
  'Squash',
  'Strawberry',
  'Sugar',
  'Sugar beet',
  'Sugarcane',
  'Sultani',
  'Sultapya',
  'Sunflower oil',
  'Sunflower seed',
  'Sweet corn',
  'Sweet Pepper',
  'Sweet potato',
  'Taro',
  'Tea',
  'Tetraodontiformes',
  'Tomato',
  'Trout',
  'Tuna',
  'Turkey',
  'Turnip leaf',
  'Turnip root',
  'Vegetable oil',
  'Walnut',
  'Water melon',
  'Watercress',
  'Welsh',
  'Wheat',
  'Whey',
  'White bean',
  'Yam',
  'Yogurt',
  'Tangerine',
  'Zucchini',
  'Hen eggs',
  'Quail eggs',
  'Poppy seed',
  'Hazelnut',
  'Non-gluten flour',
  'Mustard',
  'Herb',
  'Beef',
  'Pork',
  'Rabbit',
  'Cashew',
  'Gluten flour',
  'Pistachios',
  'Brazilian nut',
  'Sea fish',
  'Cow milk',
  'Freshwater fish',
  'Goat milk',
  'Sheep milk',
  'Chickpeas',
]

export const reactionTypes = [
  {
    value: 'Oral',
    label: 'Oral',
    key: 'Oral',
  },
  {
    value: 'Dermatological',
    label: 'Dermatological',
    key: 'Dermatological',
  },
  {
    value: 'Respiratory',
    label: 'Respiratory',
    key: 'Respiratory',
  },
  {
    value: 'Gastrological',
    label: 'Gastrological',
    key: 'Gastrological',
  },
  {
    value: 'Neurological',
    label: 'Neurological',
    key: 'Neurological',
  },
]
